version: "3.3"
services:
  app:
    image: 'amirrezabsh/project:1.0'
    container_name: app
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongonetwork
    ports:
      - "8080:8080"
  mongo:
    image: mongo:latest
    hostname: project_mongodb
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: shortUrlDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      
      #MONGO_DATABASE: kz
    networks:
      - mongonetwork
    ports:
      - 27017:27017
    volumes:
      - /opt/data/post/:/data/db
networks:
 mongonetwork:
   driver: bridge
